### ISSUE TITLE
TS03-Eu, como desenvolvedor, desejo realizar pesquisas no banco de dados utilizando o Node.js.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#100]
Critérios de aceitação:

- [ ]  pesquisar por palavra.
- [ ]  pesquisar por uma frase.
- [ ]  pesquisar por um número.
- [ ]  visualizar resultados da pesquisa.

**Comment by micheldcamargo** [comment]
Documentação do neo4j: https://neo4j.com/docs/operations-manual/current/

**Comment by micheldcamargo** [comment]
Utilizando o exemplo 'movies' do neo4j:
-Uma pesquisa básica retornando todos os membros de Pessoa que contém o texto 'Tom': 

$MATCH (person:Person) WHERE person.name CONTAINS "Tom" RETURN *
person - onde vão ficar os resultados

As pesquisas podem ser feitas usando os conectivos lógicos E/OU assim como em sql

MATCH (person:Person) WHERE person.name  CONTAINS "Dina" OR person.name CONTAINS "Tom" RETURN *
Vou tentar ver uma forma de pesquisar direto em todos os campos de PERSON.
