### ISSUE TITLE
Aprendendo como utilizar o Neo4j e o Node.js

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#104]
Video de como fazer um cadastro e utilizar o neo4j:
https://www.youtube.com/watch?v=snjnJCZhXUM

**Comment by zero101010** [comment]
Exemplo de como utilizar d3 com neo4j:
https://github.com/eisman/neo4jd3

**Comment by gustavoduartemoreira** [comment]
Um pouco sobre DB de grafos

https://www.youtube.com/watch?v=zAQs3uhE1E8

Neo4j
https://www.youtube.com/watch?v=Erm0-Hwz5s8

**Comment by gustavoduartemoreira** [comment]
Demonstração de Neo4j.

https://www.youtube.com/watch?v=XJkKRoUeOVc

https://www.youtube.com/watch?v=oplCmX1K71A

**Comment by marcos-mv** [comment]
Carregamento e Relacionamento de dados no neo4J: https://www.youtube.com/watch?v=1prQseeJvpI

**Comment by Mikhaelle** [comment]
Criando uma database com o neo4j : https://www.youtube.com/watch?v=1kyPUqU-MkE
