### ISSUE TITLE
US09-Eu, como desenvolvedor, desejo remover informações desnecessárias de projetos que serão utilizadas.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#120]
Critérios de aceitação:

- [ ]  tratar os dados de projetos para que sejam obtidos apenas os valores desejados.
- [ ]  visualizar os dados tratados.

**Comment by gustavoduartemoreira** [comment]
Dados recuperados das propostas:

PRONAC:
Segmento:
Área:
Mecanismo:
Enquadramento:
Município/UF:
Ano do projeto:
Data término:
Data início:
Valor proposta:
Valor projeto:
Valor solicitado:
Valor aprovado:
Valor captado:
