### ISSUE TITLE
US11-Eu, como desenvolvedor, desejo criar a tela de resultados da pesquisa.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#122]
Critérios de aceitação:

- [x]  lista com os resultados de pesquisa.
- [x]  exibir nome do projeto.
- [x]  exibir PRONAC.
- [x] exibir área.

**Comment by Mikhaelle** [comment]
como a gente não tem a pesquisa com os resultados da api do versalic podemos fazer com uns campos colocado a mão mesmo ?

**Comment by FilipeKN4** [comment]
Isso mesmo, por enquanto só o front-end, depois iremos fazer essa conexão de pesquisa com a página de resultados.

**Comment by Mikhaelle** [comment]
Falta subir o protótipo de baixa fidelidade atualizado
