### ISSUE TITLE
US13-Eu, como desenvolvedor, desejo criar uma API para disponibilizar as informações obtidas em formato JSON.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#128]
Critérios de aceitação:

- [ ]   subir o JSON com os dados de projetos para a API.
- [ ]   subir o JSON com os dados de proponentes para a API.
- [ ]  documentar a API.
- [ ]  verificar se é possível consumir a API corretamente.

**Comment by FabianaRibas** [comment]
https://www.django-rest-framework.org/tutorial/quickstart/

**Comment by gustavoduartemoreira** [comment]
Video motra um pouco sobre API
https://www.youtube.com/watch?v=gFsIGJR5R8I

**Comment by gustavoduartemoreira** [comment]
https://medium.com/@marcosrabaioli/criando-uma-api-rest-utilizando-django-rest-framework-parte-1-55ac3e394fa

**Comment by Mikhaelle** [comment]
POST, GETS, etc... no django rest : https://www.django-rest-framework.org/tutorial/2-requests-and-responses/

Explicação do request com exemplo de inserção de dados(post): https://pythonhelp.wordpress.com/2014/07/25/acessando-apis-rest-com-python/

**Comment by gustavoduartemoreira** [comment]
TEstar API
http://www.latrovacommits.com/pt/2017/10/21/como-testar-django-rest-framework/

**Comment by Mikhaelle** [comment]
Sobre serialização : https://medium.com/grupy-rn/criando-api-rest-com-django-rest-framework-2-10-ff920b58389e
