### ISSUE TITLE
US18-Eu, como desenvolvedor, desejo testar toda a aplicação de visualização de grafos.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#138]
Critérios de Aceitação
 
- [x] realizar todos os testes da aplicação de visualização em grafos.
- [x] obter cobertura de 90 por cento de testes.

**Comment by FabianaRibas** [comment]
Chai Assertion Library
-https://www.chaijs.com/guide/installation/

Mocha framework
-https://mochajs.org/#installation

Intro To JavaScript Unit Testing With Mocha JS & Chai:
-https://www.youtube.com/watch?v=MLTRHc5dk6s

NODE JS, MOCHA TEST:
-https://www.youtube.com/watch?v=NhlpFD5EL_Q

NODE JS, MOCHA ASYNC
-https://www.youtube.com/watch?v=aUJ2Mc-mFAw

**Comment by zero101010** [comment]
Use Mocha and Chai to test node.js   
-https://mherman.org/blog/testing-node-js-with-mocha-and-chai/
