### ISSUE TITLE
TS04-Eu, como desenvolvedor, desejo otimizar a tela de visualização dos resultados da pesquisa por meio de grafos.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#141]
## Descrição

Deseja-se detalhar e estilizar a tela de visualização em grafos para melhorar a compreensão do usuário em relação as informações dispostas.

## Tarefas

- [ ] criar tela de visualização de projeto e todos os seus atributos
- [ ] criar tela de visualização do respectivo proponente e todos os projetos que a ele pertencem

## Critérios de Aceitação 
  
- na tela de visualização de projetos todos os nós referentes ao mesmo projeto devem possuir a mesma cor
- na tela de visualização do proponente todos os nós referentes ao mesmo proponente devem possuir a mesma cor
- em ambas as telas devem haver legendas explicando o que são cada um dos nós e o que significam as ligações.

**Comment by Mikhaelle** [comment]
Lista de visualizações usando D3:
- Nesse as ligações podem colapsar mas o tamanho do nó não muda : https://bl.ocks.org/mbostock/1062288, http://bl.ocks.org/GerHobbelt/2727824
- Nesse as ligações podem colapsar e o nome do nó aparece no centro : https://bl.ocks.org/mbostock/1093130
- Nesse as ligações podem colapsar e são agrupados por cores : http://bl.ocks.org/GerHobbelt/3071239
- Nesse as ligações colapsam, o tamanho do nó muda e ele fica sempre em formato de árvore : http://bl.ocks.org/GerHobbelt/3683278
