### ISSUE TITLE
TS07-Eu, como desenvolvedor, desejo aprimorar o método de pesquisa para que possa se adequar a pesquisa de projetos.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#145]
## Descrição

Deseja-se realizar uma pesquisa dentre todos os projetos disponíveis e disponibilizar os resultados em uma lista para o usuário.

## Tarefas

- [x] tornar pesquisa não sensível a letras maiúsculas ou minúsculas
- [x] retornar lista de projetos

## Critérios de aceitação

* A pesquisa deve retornar uma lista de projetos de acordo com o parâmetro passado.
* A pesquisa deve ocorrer independentemente de existirem letras maiúsculas ou minúsculas.

**Comment by micheldcamargo** [comment]
Exemplo de pesquisa em todas as properties com uma lista de palavras: 

WITH ['pROJETO', 'PROJETO', 'projeto', 'Projeto'] AS wordlist
UNWIND wordlist AS word
WITH word
MATCH (project:Project) 
      WHERE project.nome CONTAINS word
      RETURN project.PRONAC as PRONAC, project.nome as Nome, project.area as Área ORDER BY project.nome

**Comment by gustavoduartemoreira** [comment]
Pesquisa realizada com sucesso!
