### ISSUE TITLE
US20-Eu, como desenvolvedor, desejo documentar a API criada para fornecer detalhes das informações disponibilizadas de projetos e proponentes.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#146]
## Descrição

Deseja-se realizar a descrição de forma detalhada dos endpoints de projetos e proponentes disponíveis na API. (É possível utilizar o Swagger para essa atividade)

## Tarefas

- [x] descrever todos os endpoints de proponentes
- [x] descrever todos os endpoints de projetos

## Critérios de aceitação

* Deve haver uma descrição geral sobre o que são proponentes.
* Deve haver uma descrição de todos os atributos de proponentes.
* Deve haver descrição geral sobre o que são projetos.
* Deve haver descrição de todos os atributos de projetos.

**Comment by FilipeKN4** [comment]
https://swagger.io/ essa ferramenta será utilizada para fazer isso.

**Comment by FabianaRibas** [comment]
Documentação Django API rest: Documenting your API https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by marcos-mv** [comment]
Playlist com tutorial para utilização do swagger.
https://www.youtube.com/playlist?list=PLnBvgoOXZNCOiV54qjDOPA9R7DIDazxBA
