### ISSUE TITLE
TS11-Eu, como desenvolvedor, desejo realizar a conversão dos dados do proponente e os respectivos projetos selecionados para o formato de json suportado pelo D3.js.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#157]
# Descrição

Deseja-se tornar possível a geração de uma visualização em grafos utilizando o D3.js obtendo dados de pesquisa do Neo4j como entrada, por meio da conversão desses dados para o formato json suportado pela biblioteca.

# Tarefas

- [x] adaptar o método de conversão do Neo4j para o D3.js para que receba dados provenientes de pesquisa na linguagem cypher
- [x] gerar o botão que permite visualizar o grafo de resultados

# Critérios de Aceitação

- a visualização em grafos deve ser possível a partir do pressionar do botão de "visualizar".

**Comment by gustavoduartemoreira** [comment]
Foi fechada na US21!
