### ISSUE TITLE
Retirar o CheckBox da pág principal(proposta / proponente).

### ISSUE THREAD

**Issue by marcos-mv** [fga-eps-mds/2018.2-NaturalSearch#170]
# Tarefa

Considerando a mudança na forma da pesquisa no banco essas checkBox presentes na home não são mais necessárias.

- [x] - Retirar o checkBox mantendo a página em pleno funcionamento e responsividade.

**Comment by gustavoduartemoreira** [comment]
Corrigido na US-21
