### ISSUE TITLE
Estudando Circle CI para definir se é melhor utilizar utilizar ele ou Travis CI

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#25]

**Comment by victorcmoura** [comment]
Fiz esse material com o meu grupo de Testes de Software semestre passado. Talvez possa ser útil.
[Integração contínua com CircleCI (1).pdf](https://github.com/fga-eps-mds/2018.2-NaturalSearch/files/2337229/Integracao.continua.com.CircleCI.1.pdf)

**Comment by victorcmoura** [comment]
Arrumem o título. CircleCI*
