### ISSUE TITLE
Pesquisas sobre Sistemas de Recomendação, Machine Learning e Visualização em Grafos

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#27]
Insiram links úteis para a definição do nosso escopo e formas de como pode construir nossa aplicação.

**Comment by FilipeKN4** [comment]
[Sistemas de Recomendação - Como funcionam?](http://igti.com.br/blog/como-funcionam-os-sistemas-de-recomendacao/)

**Comment by marcos-mv** [comment]
https://goo.gl/C6BLta Utilizando processamento de linguagem natural para criar um sumarização automática de textos. Python

**Comment by marcos-mv** [comment]
https://goo.gl/UmKsTR Lista de algumas metodologias utilizadas para processamento de textos em linguagem natural

**Comment by FilipeKN4** [comment]
Sitemas de recomendação, a parte de sistemas de conteúdo me parece próxima do nosso objetivo 
https://pt.linkedin.com/pulse/machine-learning-para-sistemas-de-recomenda%C3%A7%C3%A3o-marco-garcia

**Comment by FilipeKN4** [comment]
Esse curso do DataCamp me parece ser o que precisamos para encontrar a similaridade entre os conteúdos do Versalic:
 https://www.datacamp.com/community/tutorials/recommender-systems-python
