### ISSUE TITLE
Pesquisando ferramentas para visualização de dados em forma de grafo

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#33]

**Comment by zero101010** [comment]
http://arborjs.org/

**Comment by zero101010** [comment]
http://sigmajs.org/

**Comment by zero101010** [comment]
https://www.youtube.com/watch?v=r9JCzzWQG18

**Comment by zero101010** [comment]
http://arborjs.org/reference

**Comment by zero101010** [comment]
https://www.youtube.com/watch?v=NdRt2B7K8qc

**Comment by RochaCarla** [comment]
Dêem uma olhada no elastic search + kibana (visualizacao um pouco mais BI)

**Comment by marcos-mv** [comment]
https://www.youtube.com/watch?v=4tAOA7Skqtw

**Comment by zero101010** [comment]
https://www.elastic.co/webinars/sneak-peek-of-graph-capabilities-with-elasticsearch

**Comment by zero101010** [comment]
https://imasters.com.br/desenvolvimento/elasticsearch-como-criar-seu-servidor-de-busca-e-ter-um-site-ate-278-vezes-mais-rapido
