### ISSUE TITLE
Aprendendo HTML e CSS.

### ISSUE THREAD

**Issue by marcos-mv** [fga-eps-mds/2018.2-NaturalSearch#45]
Link de alguns Cursos de HTML.
https://www.youtube.com/watch?v=epDCjksKMok&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o

https://pt.khanacademy.org/computing/computer-programming/html-css

**Comment by Mikhaelle** [comment]
Outros links de cursos em HTML 
- https://www.udemy.com/html-and-css-for-beginners-crash-course-learn-fast-easy/learn/v4/overview
