### ISSUE TITLE
Completando documento de arquitetura

### ISSUE THREAD

**Issue by Mikhaelle** [fga-eps-mds/2018.2-NaturalSearch#52]

**Comment by Mikhaelle** [comment]
documentação do django :
- https://django-book.readthedocs.io/en/latest/chapter01.html

**Comment by Mikhaelle** [comment]
@zero101010 a gente pode conversar amanhã se der ? to com mts duvidas na arquitetura

**Comment by zero101010** [comment]
@Mikhaelle podemos sim,só me avisar o horário que tento te ajudar a sanar as dúvidas

**Comment by Mikhaelle** [comment]
Documentos de arquitetura com django :+1: 
- https://github.com/fga-eps-mds/fisCAE-2017-2/wiki/Documento-de-arquitetura
- https://github.com/fga-eps-mds/2017.1-PlataformaJogosUnB/wiki/Documento-de-Arquitetura
- https://fga-eps-mds.github.io/2018.1-Dr-Down/mds/ARCHITECTURE_DOCUMENT/#3-requisitos-e-restricoes-arquiteturais
