### ISSUE TITLE
US01-Eu, como usuário, desejo realizar uma pesquisa com qualquer palavra, frase, ou número que interessar

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#63]
Critérios de aceitação:

- [ ]  pesquisar por palavra.
- [ ]  pesquisar por uma frase.
- [ ]  pesquisar por um número.
- [ ]  visualizar resultados da pesquisa.

**Comment by FilipeKN4** [comment]
Um campo de pesquisa único, onde caso o usuário informe uma palavra, frase ou número deve existir retorno de projetos e propostas. Criem telas descartáveis apenas para testar a pesquisa e os resultados.

**Comment by zero101010** [comment]
https://docs.djangoproject.com/pt-br/2.0/topics/db/search/

**Comment by FilipeKN4** [comment]
Por um erro foi criada outra issue para essa história, sendo assim, essa será fechada.
