### ISSUE TITLE
US02-Eu, como desenvolvedor, desejo criar uma tabela de projetos no banco de dados da aplicação.

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#64]
Critérios de aceitação:

- [x] criar a tabela com todos os atributos existentes na API Salic. 
- [x] verificar se os objetos do tipo projeto são criados corretamente.

**Comment by FilipeKN4** [comment]
Critérios de aceitação:

- [ ] criar a tabela com todos os atributos existentes na API Salic. 
- [ ] verificar se os objetos do tipo projeto são criados corretamente.

**Comment by FilipeKN4** [comment]
Verifiquem se é possível criar um projeto utilizando o Django Admin
