### ISSUE TITLE
US03-Eu, como desenvolvedor, desejo criar uma tabela de propostas no banco de dados da aplicação.

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#65]
Critérios de aceitação:

- [x] criar a tabela com todos os atributos existentes na API Salic.
- [x] verificar se é está sendo possível criar objetos do tipo proposta.

**Comment by FilipeKN4** [comment]
Critérios de aceitação:

- [ ] criar a tabela com todos os atributos existentes na API Salic.
- [ ] verificar se é está sendo possível criar objetos do tipo proposta.

**Comment by FilipeKN4** [comment]
Utilizem o Django Admin para verificar a criação de propostas.

**Comment by Mikhaelle** [comment]
http://api.salic.cultura.gov.br/doc/

**Comment by micheldcamargo** [comment]
https://tutorial.djangogirls.org/pt/django_models/
