### ISSUE TITLE
US04-Eu, como desenvolvedor, desejo criar uma tela inicial para visualizar informações gerais sobre o produto.

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#66]
Critérios de aceitação:

- [x] criar campo para pesquisa.
- [x] selecionar pesquisa apenas de projetos.
- [x] selecionar pesquisa apenas de propostas.
- [x] selecionar pesquisa de projetos e propostas.
- [x] descrição do produto.

**Comment by FilipeKN4** [comment]
Critérios de aceitação:

- [ ] selecionar pesquisa apenas de projetos.
- [ ] selecionar pesquisa apenas de propostas.
- [ ] selecionar pesquisa de projetos e propostas.
- [ ] descrição do produto.
