### ISSUE TITLE
US05-Eu, como desenvolvedor, desejo criar a tela de visualização dos resultados da pesquisa por meio de grafos.

### ISSUE THREAD

**Issue by zero101010** [fga-eps-mds/2018.2-NaturalSearch#67]
Critérios de aceitação:

- [ ] visualizar os resultados da pesquisa em forma de grafos.
- [ ] criar campo para realizar nova pesquisa.
- [ ] realizar nova pesquisa apenas por projetos.
- [ ] realizar nova pesquisa apenas por propostas.
- [ ] realizar nova pesquisa entre projetos e propostas.

**Comment by FilipeKN4** [comment]
Critérios de aceitação:

- [ ] visualizar os resultados da pesquisa em forma de grafos.
- [ ] criar campo para realizar nova pesquisa.
- [ ] realizar nova pesquisa apenas por projetos.
- [ ] realizar nova pesquisa apenas por propostas.
- [ ] realizar nova pesquisa entre projetos e propostas.

**Comment by FilipeKN4** [comment]
Por um erro foi criado uma nova issue para esta história, sendo assim, essa será fechada.
