### ISSUE TITLE
Doc Arquitetura

### ISSUE THREAD

**Issue by mbslet** [fga-eps-mds/2018.2-NaturalSearch#72]
O documento de Arquitetura não está finalizado, certo?
Sugiro que terminem o quanto antes e não deixem acumular para outras sprints, isso pode acontecer diversas vezes mas é um tempo que fará falta hehe

Caso esteja finalizado já subam para o repo, porque o que eu tava lendo ainda tem umas seções vazias... 
tamo junto #pas

**Comment by zero101010** [comment]
O documento de arquitetura ainda não está finalizado,pois tivemos que fazer algumas modificações, a mais significativa foi a mudança do Banco de dados no entanto até o final dessa Sprint a primeira versão estará finalizada.
