### ISSUE TITLE
US06-Eu, como desenvolvedor, desejo consumir dados de projetos da API Salic

### ISSUE THREAD

**Issue by tacia68** [fga-eps-mds/2018.2-NaturalSearch#82]
Critérios de aceitação:

- [x]  puxar os dados de projetos da API.
- [x]  tratar os dados para que sejam obtidos apenas os valores desejados.
- [x]  visualizar os dados tratados.

**Comment by Mikhaelle** [comment]
documentação do request:
- http://docs.python-requests.org/pt_BR/latest/#
documentação do json:
- https://docs.python.org/3.6/library/json.html
utilidades:
- https://stackoverflow.com/questions/16877422/whats-the-best-way-to-parse-a-json-response-from-the-requests-library
