### ISSUE TITLE
US01-Eu, como usuário, desejo realizar uma pesquisa com qualquer palavra, frase, ou número que interessar

### ISSUE THREAD

**Issue by tacia68** [fga-eps-mds/2018.2-NaturalSearch#85]
Critérios de aceitação:

- [x]  pesquisar por palavra.
- [x]  pesquisar por uma frase.
- [x]  pesquisar por um número.
- [x]  visualizar resultados da pesquisa.

**Comment by FabianaRibas** [comment]
Fontes de pesquisa:
- [https://docs.djangoproject.com/pt-br/2.1/topics/db/search/](url)
- [https://docs.djangoproject.com/en/2.1/topics/db/sql/](url)
- [https://docs.djangoproject.com/en/2.1/topics/db/queries/](url)
- [https://docs.djangoproject.com/en/2.1/topics/db/queries/#filtered-querysets-are-unique](url)
- [https://www.calazan.com/adding-basic-search-to-your-django-site/](url)
- [https://djangopackages.org/packages/p/django-simple-search/](url)

**Comment by micheldcamargo** [comment]
Devido à mudança na arquitetura utilizaremos somente a lógica desta US.
