### ISSUE TITLE
TS02-Eu, como desenvolvedor, desejo consumir os dados de projetos e propostas utilizando o Node.js.

### ISSUE THREAD

**Issue by FilipeKN4** [fga-eps-mds/2018.2-NaturalSearch#99]
Critérios de aceitação:

- [x]  puxar os dados de projetos da API.
- [x]  tratar os dados para que sejam obtidos apenas os valores desejados.
- [x]  visualizar os dados tratados.

**Comment by gustavoduartemoreira** [comment]
A API Salic não está fora. Não é possível recuperar dados!

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://api.salic.cultura.gov.br/v1/swagger-def/"}]}

![image](https://user-images.githubusercontent.com/32913216/46211509-125d6500-c30a-11e8-8ece-6274bef9d8dc.png)

![image](https://user-images.githubusercontent.com/32913216/46211429-e5a94d80-c309-11e8-8a29-ab2a27c6016e.png)

**Comment by gustavoduartemoreira** [comment]
Aberta uma Issue no git da API SALIC 
[Issue #91](https://github.com/lappis-unb/salic-api/issues/91)

**Comment by micheldcamargo** [comment]
Issue
